## This is from Biostrings
GENETIC_CODE <- structure(c(
  TTT = "F", TTC = "F", TTA = "L", TTG = "L", TCT = "S", 
  TCC = "S", TCA = "S", TCG = "S", TAT = "Y", TAC = "Y", TAA = "*", 
  TAG = "*", TGT = "C", TGC = "C", TGA = "*", TGG = "W", CTT = "L", 
  CTC = "L", CTA = "L", CTG = "L", CCT = "P", CCC = "P", CCA = "P", 
  CCG = "P", CAT = "H", CAC = "H", CAA = "Q", CAG = "Q", CGT = "R", 
  CGC = "R", CGA = "R", CGG = "R", ATT = "I", ATC = "I", ATA = "I", 
  ATG = "M", ACT = "T", ACC = "T", ACA = "T", ACG = "T", AAT = "N", 
  AAC = "N", AAA = "K", AAG = "K", AGT = "S", AGC = "S", AGA = "R", 
  AGG = "R", GTT = "V", GTC = "V", GTA = "V", GTG = "V", GCT = "A", 
  GCC = "A", GCA = "A", GCG = "A", GAT = "D", GAC = "D", GAA = "E", 
  GAG = "E", GGT = "G", GGC = "G", GGA = "G", GGG = "G"), 
  alt_init_codons = c("TTG", 
                      "CTG")
)

#' Collapse counts by mutated amino acid
#' 
#' @param se A \code{\link[SummarizedExperiment]{SummarizedExperiment}}
#'   generated by \code{\link{summarizeExperiment}}
#' 
#' @return A \code{\link[SummarizedExperiment]{SummarizedExperiment}} where
#'   counts have been aggregated by the mutated amino acid(s).
#'   
#' @author Charlotte Soneson, Michael Stadler
#' 
#' @export
#' 
#' @importFrom Matrix.utils aggregate.Matrix
#' @importFrom utils relist
#' @importFrom S4Vectors unstrsplit metadata
#' @importFrom SummarizedExperiment assay SummarizedExperiment colData 
#' 
collapseMutantsByAA <- function(se) {
  ## Replace codon by corresponding amino acid
  tmp <- base::strsplit(rownames(se), split = "_", fixed = TRUE)
  unl <- base::unlist(tmp, use.names = FALSE)
  unl <- paste0(base::substr(unl, 1, nchar(unl) - 3), 
                GENETIC_CODE[base::substr(unl, nchar(unl) - 2, nchar(unl))])
  tmp <- utils::relist(unl, skeleton = tmp)
  tmp <- S4Vectors::unstrsplit(tmp, sep = "_")
  tmp[rownames(se) == "WT"] <- "WT"

  ## Collapse counts
  collapsedCounts <- Matrix.utils::aggregate.Matrix(
    x = SummarizedExperiment::assay(se, "counts"), 
    groupings = factor(tmp), 
    fun = "colSums") 
  
  ## Create SummarizedExperiment
  SummarizedExperiment::SummarizedExperiment(
    assays = list(counts = collapsedCounts),
    colData = SummarizedExperiment::colData(se), 
    metadata = S4Vectors::metadata(se)
  )
}