#' Collapse counts by mutated amino acid
#'
#' @param se A \code{\link[SummarizedExperiment]{SummarizedExperiment}}
#'     generated by \code{\link{summarizeExperiment}}
#' @param nameCol A character scalar providing the column of 
#'     \code{rowData(se)} that contains the amino acid mutant names (that will 
#'     be the new row names).
#'
#' @return A \code{\link[SummarizedExperiment]{SummarizedExperiment}} where
#'     counts have been aggregated by the mutated amino acid(s).
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @export
#'
#' @importFrom Matrix.utils aggregate.Matrix
#' @importFrom utils relist
#' @importFrom S4Vectors unstrsplit metadata
#' @importFrom SummarizedExperiment assay SummarizedExperiment colData
#'
collapseMutantsByAA <- function(se, nameCol = "mutantNameAA") {
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = nameCol, type = "character")
    
    SummarizedExperiment::rowData(se)$collapseCol <- 
        vapply(SummarizedExperiment::rowData(se)[[nameCol]], 
               function(w) w[[1]], "")

    ## Collapse assays
    aList <- lapply(SummarizedExperiment::assays(se), function(a) {
        Matrix.utils::aggregate.Matrix(
            x = a,
            groupings = factor(SummarizedExperiment::rowData(se)$collapseCol),
            fun = "colSums")
    })
    
    ## Collapse rowData
    rd <- as.data.frame(SummarizedExperiment::rowData(se)) %>%
        dplyr::group_by(.data$collapseCol) %>%
        dplyr::summarize(across(everything(), function(x) paste(x, collapse = ";"))) %>%
        as.data.frame() %>%
        tibble::column_to_rownames("collapseCol")

    ## Create SummarizedExperiment
    SummarizedExperiment::SummarizedExperiment(
        assays = aList,
        colData = SummarizedExperiment::colData(se),
        metadata = S4Vectors::metadata(se),
        rowData = DataFrame(rd[rownames(aList[[1]]), ])
    )
}