#' Plot distribution of observed values
#' 
#' @param se A \code{SummarizedExperiment} object, typically generated by 
#'     \code{summarizeExperiment()}.
#' @param selAssay Character scalar specifying the assay in \code{se} to 
#'     use for the plotting.
#' @param groupBy Character scalar specifying a column from 
#'     \code{colData(se)} to use for coloring or stratifying the plots. 
#' @param plotType Character scalar specifying the type of plot to construct. 
#'     Either \code{'density'}, \code{'histogram'} or \code{'knee'}.
#' @param facet Logical scalar, indicating whether or not to facet the plot
#'     by the values specified in the \code{groupBy} column.
#' @param pseudocount Numeric scalar, representing the number to add to the 
#'     observed values in the \code{selAssay} assay before plotting. 
#' 
#' @export
#' @author Charlotte Soneson
#' 
#' @return A ggplot object.
#' 
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr gather
#' @importFrom dplyr group_by arrange mutate desc ungroup left_join
#' @importFrom SummarizedExperiment colData assay
#' @importFrom ggplot2 ggplot scale_x_log10 scale_y_log10 labs geom_line 
#'     facet_wrap geom_density geom_histogram theme_minimal theme 
#'     element_text aes
#' @importFrom rlang .data
#' 
plotDistributions <- function(se, selAssay = "counts", 
                              groupBy = NULL, plotType = "density", 
                              facet = FALSE, pseudocount = 0) {
    stopifnot(is(se, "SummarizedExperiment"))
    stopifnot(is.character(selAssay) && length(selAssay) == 1 && 
                  selAssay %in% SummarizedExperiment::assayNames(se))
    stopifnot(is.null(groupBy) ||
                  (is.character(groupBy) && length(groupBy) == 1 && 
                       groupBy %in% colnames(SummarizedExperiment::colData(se))))
    stopifnot(is.character(plotType) && length(plotType) == 1 && 
                  plotType %in% c("density", "knee", "histogram"))
    stopifnot(is.logical(facet) && length(facet) == 1)
    stopifnot(is.numeric(pseudocount) && pseudocount >= 0)
    
    ## Define a common theme to use for the plots
    commonTheme <- list(
        ggplot2::theme_minimal(),
        ggplot2::theme(axis.text = ggplot2::element_text(size = 12),
                       axis.title = ggplot2::element_text(size = 14))
    )
    
    df <- as.data.frame(as.matrix(
        SummarizedExperiment::assay(se, selAssay, withDimnames = TRUE)
    )) %>%
        tibble::rownames_to_column("feature") %>%
        tidyr::gather(key = "Name", value = "value", -feature) %>%
        dplyr::group_by(Name) %>%
        dplyr::arrange(dplyr::desc(value)) %>%
        dplyr::mutate(idx = seq_along(value), value = value + pseudocount) %>%
        dplyr::ungroup() %>%
        dplyr::left_join(as.data.frame(SummarizedExperiment::colData(se)),
                         by = "Name")
    
    ## If the user doesn't explicitly group by any variable, impose grouping
    ## by the sample ID. In that case, don't color by sample ID if facetting
    ## is used (only one curve per facet). If a variable to group by is 
    ## specified, color by sample ID even if facetting is used. 
    if (is.null(groupBy)) {
        groupBy <- "Name"
        colorFacetByName <- FALSE
    } else {
        colorFacetByName <- TRUE
    }
    
    ## Specify plot depending on desired type
    if (plotType == "knee") {
        gg <- ggplot2::ggplot(df, ggplot2::aes(x = idx, y = value)) + 
            ggplot2::scale_x_log10() + ggplot2::scale_y_log10() + 
            ggplot2::labs(x = "Feature (sorted)", 
                          y = paste0(selAssay, 
                                     ifelse(pseudocount == 0, 
                                            "", paste0(" + ", pseudocount))))
        if (facet) {
            if (colorFacetByName) {
                gg <- gg + ggplot2::geom_line(ggplot2::aes(color = .data$Name))
            } else {
                gg <- gg + ggplot2::geom_line(ggplot2::aes(group = .data$Name))
            }
            gg <- gg + 
                ggplot2::facet_wrap(~ .data[[groupBy]])
        } else {
            gg <- gg + ggplot2::geom_line(ggplot2::aes(group = .data$Name, 
                                                       color = .data[[groupBy]]))
        }
    } else if (plotType == "density") {
        gg <- ggplot2::ggplot(df, ggplot2::aes(x = value)) + 
            ggplot2::scale_x_log10() + 
            ggplot2::labs(x = paste0(selAssay, 
                                     ifelse(pseudocount == 0, 
                                            "", paste0(" + ", pseudocount))),
                          y = "Density")
        if (facet) {
            if (colorFacetByName) {
                gg <- gg + ggplot2::geom_density(ggplot2::aes(color = .data$Name))
            } else {
                gg <- gg + ggplot2::geom_density(ggplot2::aes(group = .data$Name))
            }
            gg <- gg + 
                ggplot2::facet_wrap(~ .data[[groupBy]])
        } else {
            gg <- gg + ggplot2::geom_density(ggplot2::aes(group = .data$Name, 
                                                          color = .data[[groupBy]]))
        }
    } else if (plotType == "histogram") {
        gg <- ggplot2::ggplot(df, ggplot2::aes(x = value)) + 
            ggplot2::scale_x_log10() + 
            ggplot2::labs(x = paste0(selAssay, 
                                     ifelse(pseudocount == 0, 
                                            "", paste0(" + ", pseudocount))),
                          y = "Count")
        if (facet) {
            if (colorFacetByName) {
                gg <- gg + ggplot2::geom_histogram(ggplot2::aes(fill = .data$Name), bins = 50)
            } else {
                gg <- gg + ggplot2::geom_histogram(ggplot2::aes(group = .data$Name), bins = 50)
            }
            gg <- gg +
                ggplot2::facet_wrap(~ .data[[groupBy]])
        } else {
            gg <- gg + ggplot2::geom_histogram(ggplot2::aes(group = .data$Name,
                                                            fill = .data[[groupBy]]))
        }
    } else {
        stop("Unknown 'plotType' (should be 'knee', 'density' or 'histogram').")
    }
    
    gg + commonTheme
}