# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compareCodonPositions <- function(a, b) {
    .Call(`_mutscan_compareCodonPositions`, a, b)
}

digestFastqsCpp <- function(experimentType, fastqForward, fastqReverse, skipForward = 1L, skipReverse = 1L, umiLengthForward = 10L, umiLengthReverse = 8L, constantLengthForward = 18L, constantLengthReverse = 20L, variableLengthForward = 96L, variableLengthReverse = 96L, adapterForward = "", adapterReverse = "", wildTypeForward = "", wildTypeReverse = "", constantForward = "", constantReverse = "", avePhredMin = 20.0, variableNMax = 0L, umiNMax = 0L, nbrMutatedCodonsMax = 1L, forbiddenMutatedCodons = "NNW", mutatedPhredMin = 0.0, verbose = FALSE) {
    .Call(`_mutscan_digestFastqsCpp`, experimentType, fastqForward, fastqReverse, skipForward, skipReverse, umiLengthForward, umiLengthReverse, constantLengthForward, constantLengthReverse, variableLengthForward, variableLengthReverse, adapterForward, adapterReverse, wildTypeForward, wildTypeReverse, constantForward, constantReverse, avePhredMin, variableNMax, umiNMax, nbrMutatedCodonsMax, forbiddenMutatedCodons, mutatedPhredMin, verbose)
}

