# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compareCodonPositions <- function(a, b, mutNameDelimiter) {
    .Call(`_mutscan_compareCodonPositions`, a, b, mutNameDelimiter)
}

test_mergeReadPairPartial <- function(seqF, qualF, seqR, qualR, minOverlap = 0L, maxOverlap = 0L, maxFracMismatchOverlap = 0, greedy = TRUE) {
    .Call(`_mutscan_test_mergeReadPairPartial`, seqF, qualF, seqR, qualR, minOverlap, maxOverlap, maxFracMismatchOverlap, greedy)
}

findClosestRefSeq <- function(varSeq, wtSeq) {
    .Call(`_mutscan_findClosestRefSeq`, varSeq, wtSeq)
}

digestFastqsCpp <- function(fastqForward, fastqReverse, mergeForwardReverse, minOverlap, maxOverlap, maxFracMismatchOverlap, greedyOverlap, revComplForward, revComplReverse, skipForward, skipReverse, umiLengthForward, umiLengthReverse, constantLengthForward, constantLengthReverse, variableLengthForward, variableLengthReverse, adapterForward, adapterReverse, primerForward, primerReverse, wildTypeForward, wildTypeReverse, constantForward, constantReverse, avePhredMinForward = 20.0, avePhredMinReverse = 20.0, variableNMaxForward = 0L, variableNMaxReverse = 0L, umiNMax = 0L, nbrMutatedCodonsMaxForward = 1L, nbrMutatedCodonsMaxReverse = 1L, forbiddenMutatedCodonsForward = "NNW", forbiddenMutatedCodonsReverse = "NNW", mutatedPhredMinForward = 0.0, mutatedPhredMinReverse = 0.0, mutNameDelimiter = ".", maxNReads = -1L, verbose = FALSE) {
    .Call(`_mutscan_digestFastqsCpp`, fastqForward, fastqReverse, mergeForwardReverse, minOverlap, maxOverlap, maxFracMismatchOverlap, greedyOverlap, revComplForward, revComplReverse, skipForward, skipReverse, umiLengthForward, umiLengthReverse, constantLengthForward, constantLengthReverse, variableLengthForward, variableLengthReverse, adapterForward, adapterReverse, primerForward, primerReverse, wildTypeForward, wildTypeReverse, constantForward, constantReverse, avePhredMinForward, avePhredMinReverse, variableNMaxForward, variableNMaxReverse, umiNMax, nbrMutatedCodonsMaxForward, nbrMutatedCodonsMaxReverse, forbiddenMutatedCodonsForward, forbiddenMutatedCodonsReverse, mutatedPhredMinForward, mutatedPhredMinReverse, mutNameDelimiter, maxNReads, verbose)
}

